set nocompatible

filetype off
filetype plugin on
filetype indent on
filetype plugin indent off

syntax enable


" Init vim plugin bundler.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()


" shows line numbers
set number

set mouse=a

" tab size
set tabstop=8

" do not backup files
set noswapfile

set t_Co=256
colorscheme povilasb_colors

" vertical line
set colorcolumn=79
" set .java specific commands
autocmd Filetype java setlocal colorcolumn=101

" do not fill tab with spaces
set noexpandtab

" highlight search results
set hls


" copy current working directory to primary selection
command Cwd :!pwd | tr -d '\n' | xsel


" show special symbols: tabs, EOL, trailing whitespaces
set list listchars=tab:>-,eol:$,trail:.


" creates colorscheme and ensures that it is not overwritten by future color
" schemes
highlight ExtraWhitespace ctermbg=red guibg=red

" tab and eof symbols color scheme:grey
highlight NonText ctermfg=DarkGray guifg=grey
highlight SpecialKey ctermfg=DarkGray guifg=grey


" match and highlight trailing white spaces
match ExtraWhitespace /\s\+$/

" remove trailing spaces before file save
autocmd BufWritePre * :%s/\s\+$//e

" Disable YouCompleteMe extra file confirmation prompt.
let g:ycm_confirm_extra_conf = 0

set backspace=indent,eol,start

" Display current line and column numbers.
set ruler

" Automatically indent when entering new block.
set autoindent
set cindent

" Display matching bracket.
set showmatch

" While typing search pattern display matches.
set incsearch


" Display white spaces.
function! Whitespace()
	if !exists('b:ws')
		highlight Conceal ctermbg=NONE ctermfg=240 cterm=NONE guibg=NONE guifg=#585858 gui=NONE
		highlight link Whitespace Conceal
		let b:ws = 1
	endif

	syntax clear Whitespace
	syntax match Whitespace / / containedin=ALL conceal cchar=·
	setlocal conceallevel=2 concealcursor=c
endfunction

augroup Whitespace
	autocmd!
	autocmd BufEnter,WinEnter * call Whitespace()
augroup END
