---

- name: Packets | development
  dnf:
    name: >
      git,gcc,neovim,openssl-devel,clang-libs,clang-devel,perf,tig,
      redhat-rpm-config,python3-devel,libxml2-devel
    state: latest

- name: Packets | virtualization
  dnf:
    name: qemu,qemu-kvm,virt-manager,libvirt-daemon-qemu,polkit,lxpolkit
    state: latest

- name: Packets | tools
  dnf:
    name: tmux,iotop,ltrace,strace,pciutils,zsh,entr,rsync,pass,detox,snap
    state: latest

- name: Packets | Networking
  dnf:
    name: >
      wicd,wicd-curses,iwl1000-firmware,network-manager-applet,NetworkManager,
      NetworkManager-wifi,ftp,bind-utils
    state: latest

- name: Packets | GUI
  dnf:
    name: >
      xorg-x11-drv-intel,mesa-libGL.i686,mesa-dri-drivers.i686,
      dejavu-sans-mono-fonts,pavucontrol,pulseaudio,pulseaudio-module-x11,
      firefox,rxvt-unicode-256color,tigervnc
    state: latest

- name: Docker | Setup repo
  shell: dnf config-manager \
    --add-repo \
    https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false

- name: Docker | Install
  dnf:
    name: docker-ce
    state: latest

- name: User
  user:
    name: povilas
    group: povilas
    groups: wheel,libvirt,docker
    append: yes

- name: System | Timezone
  timezone:
    name: Europe/Vilnius
