# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# vim key bindings
bindkey -v
bindkey '^R' history-incremental-search-backward

. "$HOME/.cargo/env"
export BAT_THEME=OneHalfLight
export EDITOR=vim

# "Zettelkasten new"
function zkn() {
    if [ -z "$1" ] ; then
        echo "Please provide a topic."
        return 1
    fi
    topic=$1

    timestamp=`date +%s`
    if [ -z "$2" ] ; then
      timestamp=`coreutils date +%s`
    else
      given_date="$2"
      timestamp=`coreutils date -d${given_date} +%s`
    fi

    $EDITOR ~/projects/zettels/${timestamp}_${topic}.md
}

alias gc='git commit -m'
alias gb="git branch"
alias gst="git status"
alias gco="git checkout"
alias gcp="git cherry-pick"

alias uvp='uv run python'
